version: 2.1
jobs:
  build:
    docker:
      - image: monacoremo/nix:2020-01-14-f9c81b5c-circleci
    steps:
      - checkout
      - run:
          name: Install Cachix
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
      - run:
          name: Use Cachix
          command: |
            cachix use monacoremo
      - run:
          name: Pre-load Nix environment
          command: |
            nix-shell --run "echo Loaded full stack Nix environment"
      - run:
          name: Set up the test result directory structure
          command: mkdir -p test-results
      - run:
          name: Grant access to the non-root test user
          command: |
            # There must be a better way to do this...
            chown -R user:user /root/project
            chmod o+xr /root /root/project
      - run:
          name: Run tests for the basic application
          command: |
            nix-shell --run \
              'su-exec user:user daydream-tests-run --junitxml=test-results/junit.xml"'
      - store_test_results:
          path: test-results
  cachix:
    docker:
      - image: monacoremo/nix:2020-01-14-f9c81b5c-circleci
    steps:
      - checkout
      - run:
          name: Install Cachix
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
      - run:
          name: Build and cache results on Cachix
          command: |
            nix-build | cachix push monacoremo
