version: 2.1
jobs:
  test:
    docker:
      - image: monacoremo/nix:2020-04-05-05f09348-circleci
    steps:
      - checkout
      - run:
          name: Use Cachix
          command: |
            export USER=root
            cachix use monacoremo
      - run:
          name: Install the application
          command: |
            nix-env -iA deployLocal.mkEnv.bin tests.run.bin -f default.nix
      - run:
          name: Set up the test result directory structure
          command: mkdir -p env test-results
      - run:
          name: Grant access to the non-root test user
          command: |
            # There must be a better way to do this...
            chown -R user:user /root/project
            chmod o+xr /root /root/project

            # Elm needs a home directory
            mkdir -p /home/user
            chown user:user /home/user
      - run:
          name: Set up an environment
          command: |
            su-exec user:user daydream-local-mkenv . env 8000
      - run:
          name: Run tests
          command: |
            source env/env
            su-exec user:user daydream-tests-run --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: env/tests
  cachix:
    docker:
      - image: monacoremo/nix:2020-04-05-05f09348-circleci
    steps:
      - checkout
      - run:
          name: Use Cachix
          command: |
            export USER=root
            cachix use monacoremo
      - run:
          name: Build and cache results on Cachix
          command: |
            nix-build | cachix push monacoremo
workflows:
  version: 2
  build:
    jobs:
      - cachix
      - test
