version: 2.1
jobs:
  test:
    docker:
      - image: monacoremo/nix:2020-03-15-13e7a3e1-circleci
    steps:
      - checkout
      - run:
          name: Install Cachix
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
      - run:
          name: Use Cachix
          command: |
            export USER=root
            cachix use monacoremo
      - run:
          name: Install the application
          command: |
            nix-env -iA deployLocal.withTmpEnv.bin deployLocal.run tests.run -f default.nix
      - run:
          name: Set up the test result directory structure
          command: mkdir -p test-results
      - run:
          name: Grant access to the non-root test user
          command: |
            # There must be a better way to do this...
            chown -R user:user /root/project
            chmod o+xr /root /root/project

            # Elm needs a home directory
            mkdir -p /home/user
            chown user:user /home/user
      - run:
          name: Run tests
          command: |
            su-exec user:user daydream-local-withtmpenv daydream-tests-run \
              --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
  cachix:
    docker:
      - image: monacoremo/nix:2020-03-15-13e7a3e1-circleci
    steps:
      - checkout
      - run:
          name: Install Cachix
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
      - run:
          name: Use Cachix
          command: |
            export USER=root
            cachix use monacoremo
      - run:
          name: Build and cache results on Cachix
          command: |
            nix-build | cachix push monacoremo
workflows:
  version: 2
  build:
    jobs:
      - cachix
      - test
