name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v5
      with:
        name: monacoremo
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Install application
      run: nix-env -iA tests deployLocal -f default.nix
    - name: Create environment
      run: |
        mkdir env
        daydream-local-mkenv . env 8000
    - name: Run tests
      run: |
        source env/env
        daydream-tests-run --junitxml=junit.xml
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test-output
        path: env/tests
